export const OPEN_APPLET = 'OPEN_APPLET'
export const GET_ALL_APPLETS = 'GET_ALL_APPLETS'
export const SAVE_APPLET_DATA = 'SAVE_APPLET_DATA'
export const CLOSE_APPLET = 'CLOSE_APPLET'

export const ADD_DOCUMENT = 'ADD_DOCUMENT'
export const GET_DOCUMENT = 'GET_DOCUMENT'
export const GET_ALL_DOCUMENTS = 'GET_ALL_DOCUMENTS'
export const UDATE_DOCUMENT = 'UPDATE_DOCUMENT'
export const DELETE_DOCUMENT = 'DELETE_DOCUMENT'

export const ADD_FILE = 'ADD_FILE'
export const GET_FILE = 'GET_FILE'
export const UDATE_FILE = 'UPDATE_FILE'
export const DELETE_FILE = 'DELETE_FILE'

export const ADD_FOLDER = 'ADD_FOLDER'
export const GET_FOLDER = 'GET_FOLDER'
export const GET_ALL_FOLDERS = 'GET_ALL_FOLDERS'
export const UDATE_FOLDER = 'UPDATE_FOLDER'
export const DELETE_FOLDER = 'DELETE_FOLDER'

export const ADD_SHARE = 'ADD_SHARE'
export const GET_SHARE = 'GET_SHARE'
export const GET_ALL_SHARES = 'GET_ALL_SHARES'
export const UDATE_SHARE = 'UPDATE_SHARE'
export const DELETE_SHARE = 'DELETE_SHARE'

export const ADD_MESSAGE = 'ADD_MESSAGE'
export const SEND_MESSAGE = 'SEND_MESSAGE'
export const GET_MESSAGE = 'GET_MESSAGE'
export const GET_ALL_MESSAGES = 'GET_ALL_MESSAGES'
export const DELETE_MESSAGE = 'DELETE_MESSAGE'
export const REPLY_MESSAGE = 'REPLY_MESSAGE'

export const ADD_PAGE = 'ADD_PAGE'
export const GET_PAGE = 'GET_PAGE'
export const GET_ALL_PAGES = 'GET_ALL_PAGES'
export const UDATE_PAGE = 'UPDATE_PAGE'
export const DELETE_PAGE = 'DELETE_PAGE'

export const ADD_POST = 'ADD_POST'
export const GET_POST = 'GET_POST'
export const UDATE_POST = 'UPDATE_POST'
export const DELETE_POST = 'DELETE_POST'

export const ADD_COMMENT = 'ADD_COMMENT'
export const GET_COMMENT = 'GET_COMMENT'
export const UDATE_COMMENT = 'UPDATE_COMMENT'
export const DELETE_COMMENT = 'DELETE_COMMENT'

export const ADD_GROUP = 'ADD_GROUP'
export const GET_GROUP = 'GET_GROUP'
export const UDATE_GROUP = 'UPDATE_GROUP'
export const DELETE_GROUP = 'DELETE_GROUP'

export const ADD_CELL = 'ADD_CELL'
export const GET_CELL = 'GET_CELL'
export const GET_CHUNK_CELLS = 'GET_CHUNK_CELLS'
export const UDATE_CELL = 'UPDATE_CELL'
export const DELETE_CELL = 'DELETE_CELL'

export const ADD_BUILDING = 'ADD_BUILDING'
export const GET_BUILDING = 'GET_BUILDING'
export const GET_CHUNK_BUILDINGS = 'GET_CHUNK_BUILDINGS'
export const GET_ALL_BUILDINGS = 'GET_ALL_BUILDINGS'
export const UDATE_BUILDING = 'UPDATE_BUILDING'
export const DELETE_BUILDING = 'DELETE_BUILDING'

export const ADD_PATH = 'ADD_PATH'
export const GET_PATH = 'GET_PATH'
export const GET_CHUNK_PATHS = 'GET_CHUNK_PATHS'
export const GET_ALL_PATHS = 'GET_ALL_PATHS'
export const UDATE_PATH = 'UPDATE_PATH'
export const DELETE_PATH = 'DELETE_PATH'
